<?php
# Tool parameters
$toolstype = array(
		"1"=> array("buyexp"=>0,"description"=>"Giảm 3h phát triển (mỗi giai đoạn chỉ bón phân được 1 lần)","effect"=>10800,"id"=>1,"left"=>9999572,"name"=>"Thức ăn (Vừa)","order"=>3,"price"=>0,"qdprice"=>10,"status"=>1,"type"=>7,"validtime"=>0,"yqdprice"=>8),
		"2"=> array("buyexp"=>0,"description"=>"Giảm 8h phát triển (mỗi giai đoạn chỉ bón phân được 1 lần)","effect"=>28800,"id"=>2,"left"=>9999609,"name"=>"Thức ăn (Lớn)","order"=>5,"price"=>0,"qdprice"=>20,"status"=>1,"type"=>7,"validtime"=>0,"yqdprice"=>16),
		"3"=> array("buyexp"=>0,"description"=>"Giảm 12h phát triển (mỗi giai đoạn chỉ bón phân được 1 lần)","effect"=>43200,"id"=>3,"left"=>9999573,"name"=>"Thức ăn cao cấp","order"=>7,"price"=>0,"qdprice"=>30,"status"=>1,"type"=>7,"validtime"=>0,"yqdprice"=>24),
		"4"=> array("buyexp"=>0,"description"=>"Giảm 1h phát triển (mỗi giai đoạn chỉ bón phân được 1 lần)","effect"=>3600,"id"=>4,"left"=>9997337,"name"=>"Thức ăn (Nhỏ)","order"=>2,"price"=>0,"qdprice"=>4,"status"=>1,"type"=>7,"validtime"=>0,"yqdprice"=>3),
		"11"=> array("buyexp"=>0,"description"=>"Khi mua 1 bộ 5 bao Thức ăn (vừa) sẽ được tặng 2 bao cùng loại","effect"=>0,"id"=>11,"left"=>100,"name"=>"[Set 1] Thức ăn (vừa) x5","order"=>4,"price"=>0,"qdprice"=>50,"status"=>1,"type"=>10,"validtime"=>0,"yqdprice"=>40),
		"12"=> array("buyexp"=>0,"description"=>"Khi mua 5 bao Thức ăn (lớn) sẽ được tặng 2 bao cùng loại","effect"=>0,"id"=>12,"left"=>100,"name"=>"[Set 1] Thức ăn (Lớn) x5","order"=>6,"price"=>0,"qdprice"=>100,"status"=>1,"type"=>10,"validtime"=>0,"yqdprice"=>80),
		"15"=> array("buyexp"=>0,"description"=>"Khi mua 5 bao Thức ăn (vừa), 1 người hàng xóm của bạn sẽ nhận được phần Thức ăn trị giá 30 vàng","effect"=>0,"id"=>15,"left"=>9999977,"name"=>"[Set 2] Thức ăn (vừa) x5","order"=>8,"price"=>0,"qdprice"=>50,"status"=>1,"type"=>10,"validtime"=>0,"yqdprice"=>40),
		"16"=> array("buyexp"=>0,"description"=>"Khi mua 5 bao Thức ăn (lớn), 2 người hàng xóm của bạn sẽ nhận được phần Thức ăn trị giá 30 vàng","effect"=>0,"id"=>16,"left"=>9999903,"name"=>"[Set 2] Thức ăn (lớn) x5","order"=>9,"price"=>0,"qdprice"=>100,"status"=>1,"type"=>10,"validtime"=>0,"yqdprice"=>80),
		"17"=> array("buyexp"=>0,"description"=>"Gói quà trị giá 140 vàng. Bạn có thể nhận món quà này khi tham gia sự kiện.","effect"=>0,"id"=>17,"left"=>100,"name"=>"Gói quà giáng sinh","order"=>1,"price"=>0,"qdprice"=>100,"status"=>1,"tips"=>"Chỉ bán từ<font color='#FF6600'> <b>15/12/2010 đến 30/12/2010</b>.</font> Bao gồm: 3 Thức ăn (lớn) + 1 Thức ăn cao cấp + 1 Thức ăn (vừa) + 5 Thức ăn (nhỏ). Thẻ sẽ được bảo quản trong kho.","type"=>10,"validtime"=>0,"yqdprice"=>80),
		"18"=> array("buyexp"=>0,"description"=>"Gói quà trị giá 140 vàng. Bạn có thể nhận món quà này khi tham gia sự kiện.","effect"=>0,"id"=>18,"left"=>100,"name"=>"Limited Time Package New Year's Day","order"=>1,"price"=>0,"qdprice"=>100,"status"=>1,"tips"=>"Chỉ bán từ<font color='#FF6600'> <b>15/12/2010 đến 30/12/2010</b>.</font> Bao gồm: 3 Thức ăn (lớn) + 1 Thức ăn cao cấp + 1 Thức ăn (vừa) + 5 Thức ăn (nhỏ). Thẻ sẽ được bảo quản trong kho.","type"=>10,"validtime"=>0,"yqdprice"=>80),
		"19"=> array("buyexp"=>0,"description"=>"Gói quà trị giá 140 vàng. Bạn có thể nhận món quà này khi tham gia sự kiện.","effect"=>0,"id"=>19,"left"=>100,"name"=>"Limited Time Package New Year","order"=>1,"price"=>0,"qdprice"=>100,"status"=>1,"tips"=>"Chỉ bán từ<font color='#FF6600'> <b>15/12/2010 đến 30/12/2010</b>.</font> Bao gồm: 3 Thức ăn (lớn) + 1 Thức ăn cao cấp + 1 Thức ăn (vừa) + 5 Thức ăn (nhỏ). Thẻ sẽ được bảo quản trong kho.","type"=>10,"validtime"=>0,"yqdprice"=>80),
		"101"=> array("buyexp"=>0,"description"=>"Phần lương đủ chi cho 1 ngày làm việc của bảo vệ","effect"=>86400,"id"=>101,"left"=>9998988,"name"=>"Tiền lương","order"=>50,"price"=>0,"qdprice"=>4,"status"=>1,"type"=>5,"validtime"=>0,"yqdprice"=>3),
		"102"=> array("buyexp"=>0,"description"=>"Khi mua 5 phần lương (vừa) sẽ được tặng 2 phần cùng loại","effect"=>604800,"id"=>102,"left"=>9994952,"name"=>"[Set 1] Tiền lương x5","order"=>51,"price"=>0,"qdprice"=>20,"status"=>1,"type"=>5,"validtime"=>0,"yqdprice"=>16),
		"110"=> array("buyexp"=>0,"description"=>"Tôi giúp bạn canh giữ trang trại. Nhưng không trả lương thì đừng hòng bắt tôi làm việc","id"=>5,"left"=>1,"name"=>"Cao bồi","price"=>20000,"qdprice"=>0,"status"=>1,"tips"=>"Nhớ trả lương hằng ngày cho cao bồi nha","type"=>106,"validtime"=>0,"yqdprice"=>0),
		"109"=> array("buyexp"=>0,"description"=>"Tôi giúp bạn canh giữ trang trại. Nhưng không trả lương thì đừng hòng bắt tôi làm việc","id"=>4,"left"=>1,"name"=>"Phù thủy","price"=>18000,"qdprice"=>0,"status"=>1,"tips"=>"Nhớ trả lương hằng ngày cho phù thủy nha","type"=>106,"validtime"=>0,"yqdprice"=>0),
		"108"=> array("buyexp"=>0,"description"=>"Tôi giúp bạn canh giữ trang trại, nhưng không trả lương thì đừng hòng bắt tôi làm việc","id"=>3,"left"=>1,"name"=>"Tiều phu","price"=>15000,"qdprice"=>0,"status"=>1,"tips"=>"Nhớ trả lương hằng ngày cho tiều phu nha","type"=>106,"validtime"=>0,"yqdprice"=>0),
		"107"=> array("buyexp"=>0,"description"=>"Tôi giúp bạn canh giữ trang trại, nhưng không trả lương thì đừng hòng bắt tôi làm việc","id"=>2,"left"=>1,"name"=>"Thằng bé","price"=>15000,"qdprice"=>0,"status"=>1,"tips"=>"Khi thuê thằng bé sẽ được tặng phần lương trị giá 12 vàng","type"=>106,"validtime"=>259200,"yqdprice"=>0),
		"106"=> array("buyexp"=>0,"description"=>"Tôi giúp bạn canh giữ trang trại, nhưng không trả lương thì đừng hòng bắt tôi làm việc","id"=>1,"left"=>1,"name"=>"Bác nông dân","price"=>10000,"qdprice"=>0,"status"=>1,"tips"=>"Khi thuê bác nông dân sẽ được tặng phần lương trị giá 12 vàng","type"=>106,"validtime"=>259200,"yqdprice"=>0),
		"100001"=> array("appid"=>353,"attacksucc"=>100,"blood"=>12,"buyexp"=>0,"description"=>"Làm giảm 12 điểm sức khỏe của thú hoang","id"=>1,"left"=>1,"name"=>"Mũi tên đồng","price"=>0,"qdprice"=>10,"status"=>1,"tips"=>"Mỗi con chỉ có thể bắn 1 lần mà thôi","type"=>10,"validtime"=>0,"yqdprice"=>8),
		"100002"=> array("appid"=>353,"attacksucc"=>100,"blood"=>19,"buyexp"=>0,"description"=>"Làm giảm 19 điểm sức khỏe của thú hoang","id"=>2,"left"=>1,"name"=>"Mũi tên bạc","price"=>0,"qdprice"=>15,"status"=>1,"tips"=>"Mỗi con chỉ có thể bắn 1 lần mà thôi","type"=>10,"validtime"=>0,"yqdprice"=>12),
		"100003"=> array("appid"=>353,"attacksucc"=>100,"blood"=>26,"buyexp"=>0,"description"=>"Làm giảm 26 điểm sức khỏe của thú hoang","id"=>3,"left"=>1,"name"=>"Mũi tên vàng","price"=>0,"qdprice"=>20,"status"=>1,"tips"=>"Mỗi con chỉ có thể bắn 1 lần mà thôi","type"=>10,"validtime"=>0,"yqdprice"=>16),
		"100004"=> array("appid"=>353,"attacksucc"=>100,"blood"=>6,"buyexp"=>0,"description"=>"Làm giảm 6 điểm sức khỏe của thú hoang","id"=>4,"left"=>1,"name"=>"Cây rút hầm","price"=>500,"qdprice"=>0,"status"=>1,"tips"=>"Mỗi con chỉ có thể bắn 1 lần mà thôi","type"=>10,"validtime"=>0,"yqdprice"=>0)
		);
?>