<?php
//Việt hóa bởi KhongBanQuyen.com
$lang = array(

	'other' => 'Khác',
	'app_connent_ok' => 'Thông báo thành công',
	'app_connent_false' => 'Thông báo thất bại',

	'note_deleteuser' => 'Xóa thành viên',
	'note_renameuser' => 'Sửa tên thành viên',
	'note_deletefriend' => 'Xóa bạn',
	'note_gettag' => 'Get TAG',
	'note_getcreditsettings' => 'Thiết đặt nhận điểm',
	'note_updatecreditsettings' => 'Cập nhật điểm',
	'note_updateclient' => 'Cập nhật ứng dụng cache',
	'note_updatepw' => 'Cập nhật mật khẩu thành viên',
	'note_updatebadwords' => 'Cập nhật danh sách từ cấm',
	'note_updatehosts' => 'Cập nhật phân tích tên miền',
	'note_updateapps' => 'Cập nhật danh sách thành viên',
	'note_updatetagtemplate' => 'Cập nhật TAG giao diện',
	'note_list' => 'Danh sách thông cáo',
	'note_test' => 'Thử',
	'note_delete' => 'Xóa',
	'note_succeed' => 'Thông cáo thành công',
	'note_na' => 'Chưa thông cáo',
	'note_false' => 'Thông cáo thất bại',
	'note_times' => 'lần',

	'pm_from' => 'Đến từ',
	'pm_to' => 'Gửi đến',
	'pm_system' => 'Tin nhắn hệ thống',
	'pm_date' => 'Thời gian',
	'pm_daterange_1' => 'Hôm nay',
	'pm_daterange_2' => 'Hôm qua',
	'pm_daterange_3' => 'Hôm trước',
	'pm_daterange_4' => 'Tuần trước',
	'pm_daterange_5' => 'Lâu lắm rồi',
	'pm_notitle' => '[Không tiêu đề]',

	'user_add' => 'Thêm thành viên',
	'user_delete' => 'Xóa thành viên',
	'login' => 'Đăng nhập',
	'logout' => 'Thoát',
	'app_add' => 'Thêm ứng dụng',
	'app_delete' => 'Xóa ứng dụng',
	'app_edit' => 'Chỉnh sửa',
	'setting_update' => 'Cập nhật thiết đặt cơ bản',
	'setting_register_update' => 'Cập nhật thiết đặt đăng ký',
	'pm_send' => 'Gửi tin nhắn hệ thống',
	'pm_delete' => 'Xóa tin nhắn hệ thống',
	'pm_clear' => 'Dọn tin nhắn',
	'badword_add' => 'Thêm từ cấm',
	'badword_delete' => 'Xóa từ cấm',
	'admin_add' => 'Thêm quản lý',
	'admin_pw_edit' => 'Sửa mật khẩu founder',
	'admin_priv_edit' => 'Sửa quyền hạn quản lý viên',
	'domain_add' => 'Thêm tên miền',
	'domain_delete' => 'Xóa tên miền',
	'credit_addexchange' => 'Cập nhật phương án đổi điểm',
	'credit_deleteexchange' => 'Xóa phương án đổi điểm',
	'credit_sync' => 'Đồng bộ thiết đặt ứng dụng điểm',
	'db_export' => 'Sao lưu dữ liệu',
	'db_import' => 'Khôi phục dữ liệu',
	'db_delete' => 'Xóa dữ liệu',
	'note_delete' => 'Xóa thông cáo',
	'note_send' => 'Bổ sung thông cáo',
	'dumpfile_exists' => 'Sự tồn tại của sao',
	'dumpfile_not_exists' => 'Không có back-up',
);